title: 'Owens Desktop'
compute:
  - name: 'Owens Desktop'
    batch: 'owens'
    node:
      - type: 'any'
        ppn: 28
        desc: >
          Choose any type of compute node. This reduces the wait time as there
          are no node specific requirements.
      - title: 'gpu'
        type: 'gpus=1'
        ppn: 28
        desc: >
          This node includes an NVIDIA Tesla P100 GPU allowing for CUDA
          computations. There are currently only 160 of these nodes on Owens.
          These nodes don't start an X server, so visualization with hardware
          rendering is not possible yet.
      - type: 'hugemem'
        ppn: 48
        desc: >
          This node has 1.5TB of available RAM as well as 48 cores. There are
          16 of these nodes on Owens.
    pbs:
      envvars:
        DESKTOP: 'mate'
